[platformio]
src_dir = ../../

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
  -include syn_config.h
  -Iinclude
  -I../../
  -DSERIAL_TX_BUFFER_SIZE=16
  -DSERIAL_RX_BUFFER_SIZE=16
build_src_filter =
  -<*>
  +<examples/arduino_serial/src/main.cpp>
  +<syntropic/drivers/syn_gpio.c>
  +<syntropic/drivers/syn_uart.c>
  +<syntropic/util/syn_ringbuf.c>
  +<syntropic/sched/syn_sched.c>
  +<syntropic/sched/syn_timer.c>
  +<syntropic/log/syn_log.c>
  +<syntropic/cli/syn_cli.c>
  +<syntropic/util/syn_fmt.c>
  +<syntropic/output/syn_led.c>
  +<port/arduino/port_arduino.cpp>
  +<syntropic/drivers/syn_adc.c>

  +<syntropic/dsp/syn_filter.c>
  +<syntropic/dsp/syn_signal.c>
  +<syntropic/util/syn_fsm.c>
monitor_speed = 115200
